### ISSUE TITLE
this.list[e].update is not a function

### ISSUE THREAD

**Issue by moooji** [davidfig/pixi-ease#6]
This happens for me after upgrading to 2.x. It seems to happen when easings are in progress and `ease.removeAll()` or `ease.removeAllEases()` is called. 

```
this.list[e].update is not a function
    at update (/Volumes/Data/Workspace/touchtech/dsr-space-exploration/node_modules/pixi-ease/dist/ease.js:1)
    at TickerListener.emit (/Volumes/Data/Workspace/touchtech/dsr-space-exploration/node_modules/@pixi/ticker/lib/ticker.js:138)
    at Ticker.update (/Volumes/Data/Workspace/touchtech/dsr-space-exploration/node_modules/@pixi/ticker/lib/ticker.js:661)
    at Ticker._tick (/Volumes/Data/Workspace/touchtech/dsr-space-exploration/node_modules/@pixi/ticker/lib/ticker.js:367)```

**Comment by davidfig** [comment]
Are you calling removeAll/Eases within the update loop?

**Comment by davidfig** [comment]
Try v2.1.0. I made lots of bug fixes and added full test coverage. Hopefully that helps.

**Comment by davidfig** [comment]
Fixed another bug that might have caused this error. v2.2.0

**Comment by moooji** [comment]
Awesome work! Yes, this seems to be resolved now!
